parameters:
    pim_events_api.event_subscriber.akeneo_storage_utils_subscriber.class: Trilix\EventsApiBundle\EventSubscriber\AkeneoStorageUtilsSubscriber
    pim_events_api.events_handler.class: Trilix\EventsApiBundle\Model\EventsHandler
    pim_events_api.outer_event_builder.class: Trilix\EventsApiBundle\OuterEvent\OuterEventBuilder
    pim_events_api.create_event_type_payload.class: Trilix\EventsApiBundle\Model\CreateEventTypePayload
    pim_events_api.create_remove_product_event_type_payload.class: Trilix\EventsApiBundle\Model\CreateRemoveProductEventTypePayload
    pim_events_api.create_remove_event_type_payload.class: Trilix\EventsApiBundle\Model\CreateRemoveEventTypePayload
    pim_events_api.resolve_event_type.class: Trilix\EventsApiBundle\Model\ResolveEventType
    pim_events_api.event_type_configuration_list.class: Trilix\EventsApiBundle\Model\EventTypeConfigurationList
    pim_events_api.akeneo_batch_outer_event_dispatcher.class: Trilix\EventsApiBundle\Model\AkeneoBatchOuterEventDispatcher
    pim_events_api.guzzle.http_client_factory.class: Trilix\EventsApiBundle\Guzzle\GuzzleHttpClientFactory
    pim_events_api.guzzle.request_factory.class: Trilix\EventsApiBundle\Guzzle\GuzzleRequestFactory
    pim_events_api.transport_factory.http.class: Trilix\EventsApiBundle\Transport\HttpTransportFactory
    pim_events_api.transport_factory.iftt_webhooks.class: Trilix\EventsApiBundle\Transport\IFTTTWebHooksTransportFactory

services:
    pim_events_api.akeneo_batch_outer_event_dispatcher:
        class: '%pim_events_api.akeneo_batch_outer_event_dispatcher.class%'
        arguments:
            - '@security.token_storage'
            - '@akeneo_batch.job.job_instance_repository'
            - '@akeneo_batch_queue.launcher.queue_job_launcher'

    pim_events_api.event_subscriber.akeneo_storage_utils_subscriber:
        class: '%pim_events_api.event_subscriber.akeneo_storage_utils_subscriber.class%'
        arguments:
            - '@pim_events_api.events_handler'
            - '@logger'
        tags:
            - { name: kernel.event_subscriber, priority: -255 }

    pim_events_api.guzzle.http_client_factory:
        class: '%pim_events_api.guzzle.http_client_factory.class%'

    pim_events_api.guzzle.request_factory:
        class: '%pim_events_api.guzzle.request_factory.class%'

    pim_events_api.events_handler:
        class: '%pim_events_api.events_handler.class%'
        arguments:
            - '@pim_events_api.resolve_event_type'
            - '@pim_events_api.outer_event_builder'
            - '@pim_events_api.akeneo_batch_outer_event_dispatcher'
            - '@logger'

    pim_events_api.resolve_event_type:
        class: '%pim_events_api.resolve_event_type.class%'
        arguments:
            - '@pim_events_api.event_type_configuration_list'

    pim_events_api.outer_event_builder:
        class: '%pim_events_api.outer_event_builder.class%'

    pim_events_api.create_event_type_payload:
        class: '%pim_events_api.create_event_type_payload.class%'
        arguments:
            - '@pim_external_api_serializer'

    pim_events_api.create_remove_product_event_type_payload:
        class: '%pim_events_api.create_remove_product_event_type_payload.class%'

    pim_events_api.create_remove_event_type_payload:
        class: '%pim_events_api.create_remove_event_type_payload.class%'

    pim_events_api.event_type_configuration_list:
        class: '%pim_events_api.event_type_configuration_list.class%'

    pim_events_api.transport_factory.http:
        class: '%pim_events_api.transport_factory.http.class%'
        arguments:
            - '@pim_events_api.guzzle.http_client_factory'
            - '@pim_events_api.guzzle.request_factory'

    pim_events_api.transport_factory.ifttt_webhooks:
        class: '%pim_events_api.transport_factory.iftt_webhooks.class%'
        arguments:
            - '@pim_events_api.guzzle.http_client_factory'
            - '@pim_events_api.guzzle.request_factory'
